name = "FlxQTL"
uuid = "ede81e08-c6d8-4fe3-94c2-f928d9d678ed"
authors = ["Hyeonju Kim <hyeonjukm01@gmail.com>"]
version = "0.3.1"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Conda = "1.10"
DelimitedFiles = "1.9"
Distributed = "1"
Distributions = "^0.23, 0.24, 0.25"
LossFunctions = "~0.11"
PyPlot = "2.11" 
StaticArrays = "1.9"
Statistics = "1"
StatsBase = "0.33, 0.34"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
